name: torch_10
channels:
  - pytorch-nightly
  - conda-forge
  - defaults
dependencies:
  - aiosignal=1.3.1
  - anyio=3.5.0
  - appnope
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - cryptography=41.0.2
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - greenlet=2.0.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=68.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.1.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.5.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.24.0
  - jupyterlab_widgets=1.0.0
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libclang=12.0.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libffi=3.4.4
  - libgfortran
  - libgfortran5
  - libiconv=1.16
  - libllvm12=12.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - marshmallow=3.20.1
  - marshmallow-enum=1.5.1
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mypy_extensions=1.0.0
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - notebook=7.0.0
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy-base=1.25.0
  - openapi-schema-pydantic=1.2.4
  - openssl=3.1.1
  - packaging=23.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - platformdirs=2.5.2
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyqt=5.15.7
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python_abi=3.10
  - pytz=2022.7
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - send2trash=1.8.0
  - sip=6.6.2
  - six=1.16.0
  - sniffio=1.2.0
  - soupsieve=2.4
  - sqlite=3.41.2
  - stack_data=0.2.0
  - stringcase=1.2.0
  - sympy=1.12
  - tenacity=8.2.2
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - torchaudio
  - torchvision=0.15.2
  - tornado=6.2
  - traitlets=5.7.1
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_inspect=0.9.0
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=3.5.2
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiodns==3.0.0
      - aiohttp==3.8.3
      - authlib==1.2.1
      - blis==0.7.10
      - bs4==0.0.1
      - cachetools==5.3.1
      - catalogue==2.0.9
      - chardet==4.0.0
      - click==8.1.6
      - confection==0.1.0
      - cymem==2.0.7
      - dataclasses-json==0.5.13
      - datasets==2.14.1
      - dill==0.3.7
      - dnspython==2.4.1
      - elastic-transport==8.4.0
      - elasticsearch==8.9.0
      - environs==9.5.0
      - et-xmlfile==1.1.0
      - fairscale==0.4.13
      - faiss-cpu==1.7.4
      - faker==19.2.0
      - filelock==3.12.2
      - filetype==1.2.0
      - fire==0.5.0
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gensim==4.3.1
      - google-api-core==2.11.1
      - google-api-python-client==2.70.0
      - google-auth==2.22.0
      - google-auth-httplib2==0.1.0
      - googleapis-common-protos==1.60.0
      - grpcio==1.50.0
      - grpcio-tools==1.50.0
      - h11==0.14.0
      - h2==4.1.0
      - hpack==4.0.0
      - httpcore==0.17.3
      - httplib2==0.22.0
      - httpx==0.24.1
      - huggingface-hub==0.16.4
      - hyperframe==6.0.1
      - jaraco-context==4.3.0
      - joblib==1.3.1
      - langchain==0.0.249
      - langcodes==3.3.0
      - langsmith==0.0.14
      - llama-index==0.7.16
      - loguru==0.7.0
      - manifest-ml==0.0.1
      - markdown==3.4.4
      - more-itertools==10.0.0
      - mpmath==1.2.1
      - msg-parser==1.2.0
      - multidict==6.0.4
      - multiprocess==0.70.15
      - murmurhash==1.0.9
      - nltk==3.8.1
      - numpy==1.25.1
      - olefile==0.46
      - openai==0.27.8
      - openpyxl==3.1.2
      - pandas==2.0.3
      - pathy==0.10.2
      - pdf2image==1.16.3
      - pdfminer-six==20221105
      - pillow==10.0.0
      - pinecone-client==2.2.2
      - preshed==3.0.8
      - protobuf==4.23.4
      - pyarrow==12.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycares==4.3.0
      - pydantic==1.10.12
      - pymilvus==2.2.11
      - pymupdf==1.22.5
      - pypandoc==1.11
      - pyparsing==3.1.1
      - pyqt5-sip==12.11.0
      - python-docx==0.8.11
      - python-dotenv==1.0.0
      - python-edgar==3.1.3
      - python-magic==0.4.27
      - python-pptx==0.6.21
      - qdrant-client==0.11.10
      - redis==4.6.0
      - regex==2023.6.3
      - rsa==4.9
      - safetensors==0.3.1
      - scikit-learn==1.3.0
      - scipy==1.11.1
      - sec-edgar-downloader==4.3.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - setuptools==68.0.0
      - smart-open==6.3.0
      - spacy==3.6.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - sqlalchemy==2.0.19
      - sqlitedict==2.1.0
      - srsly==2.4.7
      - tabulate==0.9.0
      - termcolor==2.3.0
      - thinc==8.1.10
      - threadpoolctl==3.2.0
      - tiktoken==0.4.0
      - tokenizers==0.13.3
      - torch==1.13.1
      - tqdm==4.65.0
      - transformers==4.31.0
      - typer==0.9.0
      - tzdata==2023.3
      - ujson==5.8.0
      - unstructured==0.8.4
      - uritemplate==4.1.1
      - validators==0.20.0
      - wasabi==1.1.2
      - weaviate-client==3.22.1
      - wikipedia==1.4.0
      - wolframalpha==5.0.0
      - xlrd==2.0.1
      - xlsxwriter==3.1.2
      - xmltodict==0.13.0
      - xxhash==3.2.0
      - yarl==1.9.2

